---
- name: Deploy Nginx with EFS PVC and a sample website
  hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes

  vars:
    namespace: dante-garro-dev
    pvc_name: nginx-pvc
    pod_name: nginx-efs
    storage_class: efs-sc
    web_content: |
      <html>
        <head><title>Welcome</title></head>
        <body>
          <h1>Hello from OpenShift Nginx + EFS!</h1>
        </body>
      </html>

  tasks:

    - name: Create PersistentVolumeClaim (EFS)
      k8s:
        state: present
        namespace: "{{ namespace }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ pvc_name }}"
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: "{{ storage_class }}"

    - name: Create Nginx pod with mounted PVC and init container to copy content
      k8s:
        state: present
        namespace: "{{ namespace }}"
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ pod_name }}"
          spec:
            initContainers:
              - name: init-site
                image: alpine
                command: ["/bin/sh", "-c"]
                args:
                  - |
                    echo '{{ web_content | to_json | from_json }}' > /mnt/www/index.html
                volumeMounts:
                  - name: web-content
                    mountPath: /mnt/www
            containers:
              - name: nginx
                image: nginx
                ports:
                  - containerPort: 80
                volumeMounts:
                  - name: web-content
                    mountPath: /usr/share/nginx/html
            volumes:
              - name: web-content
                persistentVolumeClaim:
                  claimName: "{{ pvc_name }}"
