---
- name: Create a VM in OpenShift Virtualization
  hosts: localhost
  gather_facts: false
  vars:
    userdata_file: "/tmp/userdata.yaml"

  tasks:

    - name: Generate cloud-init user data from template
      ansible.builtin.template:
        src: userdata.yaml.j2
        dest: "{{ userdata_file }}"

    - name: Create secret for cloud-init user data
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudinit-userdata
            namespace: "{{ ocp_namespace }}"
          type: Opaque
          data:
            userData: "{{ lookup('file', userdata_file) | b64encode }}"
    - name: Create a RHEL VM in OpenShift
      redhat.openshift.k8s:
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ ocp_namespace }}"
            labels:
              app: "{{ vm_name }}"
              kubevirt.io/dynamic-credentials-support: 'true'
              vm.kubevirt.io/template: rhel9-server-small
              vm.kubevirt.io/template.namespace: openshift
              vm.kubevirt.io/template.revision: '1'
              vm.kubevirt.io/template.version: v0.26.0
          spec:
            runStrategy: Manual
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{ vm_name }}"
                spec:
                  sourceRef:
                    kind: DataSource
                    name: rhel9
                    namespace: openshift-virtualization-os-images
                  storage:
                    resources:
                      requests:
                        storage: 30Gi
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
                  kubevirt.io/size: small
              spec:
                architecture: amd64
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: rootdisk
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - masquerade: {}
                        model: virtio
                        name: default
                    networkInterfaceMultiqueue: true
                    rng: {}
                  features:
                    acpi: {}
                    smm:
                      enabled: true
                  firmware:
                    bootloader:
                      efi: {}
                  machine:
                    type: pc-q35-rhel9.2.0
                  memory:
                    guest: 2Gi
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                tolerations:
                  - effect: NoSchedule
                    key: sandbox-cnv
                    operator: Exists
                volumes:
                  - dataVolume:
                      name: "{{ vm_name }}"
                    name: rootdisk
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userDataBase64: |
                        IyMgdGVtcGxhdGU6IGppbmphCiNjbG91ZC1jb25maWcKdXNlcnM6CiAgLSBuYW1lOiBjbG91ZC11c2VyCiAgICBzdWRvOiBbJ0FMTD0oQUxMKSBOT1BBU1NXRDogQUxMJ10KICAgIGdyb3Vwczogd2hlZWwKICAgIHNoZWxsOiAvYmluL2Jhc2gKICAgIHNzaF9hdXRob3JpemVkX2tleXM6CiAgICAgIC0gJ3NzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQ0FRQ0g0TU1ZT2ptRHBFUTN0M0hJN0JkOFE5YVNEcW9RZVlpV0dnYVRUTHBrVDNDUDl0Z2E2dlJzeElkdjNnWS9lNTM1eDc0RjI4amtmRk9LOUtLV3hKanlwOHVoVkVNVDNleXNQd0hCMDIydEVkbk1YK2k5Y1o5bVRybmxzaTBWMnNlalNqNVU3blZkUEFudEhCZEhDMXRKUmhpUWJEQktZY0VVY3FETDZHY051RkhTcmo0YmN0WElPbm5nVm9xREtDS1dBSXN5QUhRYmZDaThUSSt6NE5mS0VjdkpsZlNBSjBGWTlCVE8ybWpVSDI3QXd3ajJQVjcwaFFjVHdqZVo2S3FOQ3lxZFhjN05XQWtGUnl0NWRoZ2VDT2N3bGY1bzU2cUNFTzdBN1QwM2tZS0I5TjAyUjJvbjdZODdBQW5zTVE1VDBQcDEvMlZFRml6Smp6M3dYVkt3V01NdEIyajcxYm1SNUtzN1Vnb2p2TUY1bGMzaXhWcFhDQXJ5aHdSa0pwRWJORWtHTkdNUUMraGV3VVFhblJtVW02cE45dzRxbU41a1ZqY0V0RDd4bnVOQ05VeWZyM1NieWR6di9uU3FaQnVIdGJDV3ZsSFd5Tnl5Z2VuYTdpamZyZWY0SGJNSFc1aGlFMHZOaVg3SzBlMzJHT21Ua0dlNkM3eDN4UGl5cEhOWkR6NWpyZ0N5Z1UxMTV2OUc2eHQzVTdrWDZrWVhQdGVqSnhLc1hCZ3I1SjZ4azJZbnMxYzR4blFTU2poWktvVEl4eG13c3duMFRKdHlzbjBwZmF0bXhmSFJ1Q1JZeWVwMG9HakxiUXRIWHBkWUc0R0NOclNkVXdxaEU0KzlNWHI5RGJ4dkdTVHdnNEpFUDhRc2M1eWF2d2QzU0puNVZJU3FhbzVlclduM1d3PT0gcnNhLWtleS0yMDI1MDcwMycKICAgIHBhc3N3ZDogMTIzcXdlCiAgICBsb2NrX3Bhc3N3ZDogZmFsc2UKCmNocGFzc3dkOgogIGxpc3Q6IHwKICAgIGNsb3VkLXVzZXI6MTIzcXdlCiAgZXhwaXJlOiBGYWxzZQ==
    - name: Wait for system to become reachable over SSH
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 180
