---
- name: Create a VM in OpenShift Virtualization
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a RHEL VM in OpenShift
      redhat.openshift.k8s:
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: dante-testing
            labels:
              app: httpd
            namespace: dante-garro-dev
          spec:
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: httpd
                image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
                ports:
                  - containerPort: 8080
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
    - name: Wait for Pod to be running
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: dante-garro-dev
        name: dante-testing
      register: pod_info
      until: pod_info.resources[0].status.phase == "Running"
      retries: 10
      delay: 3

    - name: Show Pod IP
      debug:
        msg: "The Pod IP is {{ pod_info.resources[0].status.podIP }}"