---
- name: Delete a Virtual Machine in OCP Virtualization
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete VM
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ vm_name }}"
        namespace: "{{ ocp_namespace }}"
        state: absent
