---
- name: Manual Red Hat registration test
  hosts: all
  become: true
  gather_facts: false

  vars:
    activation_key: "{{ activation_key | default(omit) }}"
    organization_id: "{{ organization_id | default(omit) }}"

  pre_tasks:
    - name: Check that activation key is defined
      fail:
        msg: "activation_key is not set"
      when: activation_key is not defined

    - name: Check that organization ID is defined
      fail:
        msg: "organization_id is not set"
      when: organization_id is not defined

    - name: Test DNS connectivity to console.redhat.com
      ansible.builtin.command: getent hosts console.redhat.com
      register: dns_check
      changed_when: false
      failed_when: dns_check.rc != 0

    - name: Test HTTPS connectivity to Red Hat
      ansible.builtin.uri:
        url: https://console.redhat.com
        method: GET
        status_code: 200
      register: redhat_conn
      failed_when: redhat_conn.status != 200
      ignore_errors: true

  tasks:
    - name: Run rhc connect
      ansible.builtin.command: >
        rhc connect
        --activation-key "{{ activation_key }}"
        --organization "{{ organization_id }}"
        --force
      register: rhc_output
      changed_when: "'Successfully connected' in rhc_output.stdout"
      ignore_errors: true

    - name: Show output of rhc connect
      debug:
        var: rhc_output

    - name: Fail if registration was not successful
      fail:
        msg: "rhc connect failed or did not return success"
      when: rhc_output.rc != 0
