---
- name: Register RHEL using rhc system role
  hosts: all
  tasks:
    - name: Registering system using activation key and organization ID
#      ansible.builtin.include_role:
      ansible.builtin.import_role:
        name: redhat.rhel_system_roles.rhc
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ activation_key }}"
        rhc_organization: "{{ organization_id }}"
        rhc_use_dbus: false
